name: CI

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./... -tags skipCi

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Run semantic-release
        if: github.repository == 'casbin/caswaf' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}